<style>
#nette-debug-panel-Neevo-Nette-DebugPanel-<?php echo $name ?> td.sql{background:white !important;min-width:200px}
#nette-debug-panel-Neevo-Nette-DebugPanel-<?php echo $name ?> td.sql span{font-size:.8em}
#nette-debug-panel-Neevo-Nette-DebugPanel-<?php echo $name ?> tr table{margin:8px 0;max-height:150px;overflow:auto}
</style>
<h1><?php echo $name ?>: <?php echo $numQueries . ($numQueries === 1 ? ' query' : ' queries'); if($totalTime) printf(', %0.3f ms', $totalTime * 1000) ?></h1>
<div class="nette-inner">
<table>
<tr>
	<th>Time (ms)</th>
	<th>SQL</th>
	<th>Rows</th>
</tr>
<?php foreach($tickets as $ticket): ?>
<tr>
	<td>
		<?php printf('%0.3f', $ticket['time'] * 1000);
		if(isset($ticket['explain'])): ?>
			<br/>
			<a href="#" class="tracy-toggle tracy-collapsed"  data-tracy-ref="^tr .nette-Neevo-Nette-DebugPanel-explain">explain</a>
		<?php endif ?>
	</td>
	<td class="sql">
		<?php echo Neevo\Manager::highlightSql($ticket['sql']);
		if(null !== $s = $ticket['source']) echo '<span>' . Tracy\Helpers::editorLink($s[0], $s[1]) . ":$s[1]</span>";
		if(isset($ticket['explain'])): ?>
			<table class="tracy-collapsed nette-Neevo-Nette-DebugPanel-explain">
				<tr>
					<th><?php echo implode('</th><th>', array_keys($ticket['explain'][0])) ?></th>
				</tr>
				<?php foreach($ticket['explain'] as $row):
					echo '<tr><td>' . implode('</td><td>', $row) . '</td></tr>';
				endforeach ?>
			</table>
		<?php endif ?>
	</td>
	<td><?php echo $ticket['rows'] ?></td>
</tr>
<?php endforeach ?>
</table>
</div>
